### PR TITLE
feat: add level4headingstags option

### LINKED ISSUE #22: Strange handling of level 4 headings
this markdown

```markdown
### Color set specific config options
#### Mellifluous
default config:
```

in vimdoc looks like this:

image

I think level 4 headings should be converted in the same style as level 3 headings or level 5 headings:
```diff
diff --git a/scripts/panvimdoc.lua b/scripts/panvimdoc.lua
index 69dfaa3..6dfd726 100644
--- a/scripts/panvimdoc.lua
+++ b/scripts/panvimdoc.lua
@@ -375,19 +375,9 @@ function Header(lev, s, attr)
     return left .. " ~"
   end
   if lev == 4 then
-    left = ""
-    current_element = s
-    right = string.gsub(s, "{.+}", "")
-    right = string.gsub(right, "%[.+%]", "")
-    right = string.gsub(right, "^%s*(.-)%s*$", "%1")
-    right = string.gsub(right, "%s", "-")
-    right = string.format("*%s-%s*", stringify(meta.project), right)
-    if attr.doc then
-      right = right .. " *" .. attr.doc .. "*"
-    end
-    padding = string.rep(" ", 78 - #left - #right)
-    local r = string.format("%s%s%s", left, padding, right)
-    return r
+    left = string.upper(s)
+    current_element = nil
+    return left -- .. " ~"?
   end
   if lev >= 5 then
     left = string.upper(s)
```

### PR DESCRIPTION
**Pull request by ramojus**
fixes #22

### CODE REVIEW

**Comment by ramojus** [comment]
I think there are two problems with the changes I've made so far.

First problem:
Right now, if `level4headingstags` option is set to `false`, level 4 headings are rendered as all caps. But if `level4headingstags` option is unset or set to `true`, level 4 headings are rendered as regular text (below their tag). I think that no matter what the option is set to, these headings always be rendered either as normal text or as all caps.

Second problem:
Text right after the title is on the same line as the title and the title is two lines below the tag (it's not even clear that it's a title).
markdown:
```markdown
#### title four
some content in section four
```
vimdoc:
```vimdoc
                                                      *test-plugin-title-four*

title four                             some content in section four
```

I think there are three sensible ways fix these problems:
When `level4headingstags` option is `true`:
1. Handle level 4 headings in the same way as level 2 (excluding toc).
2. Render level 4 headings in the same line as their tag and as normal text. Only fixes the second problem, but maybe that's fine.
3. Hide level 4 heading and only show the tag.

I would be leaning towards the first two ways (but a bit more towards the first one). What do you think?

**Comment by kdheepak** [comment]
Thanks for the PR, and for trying to figure out what was going on here. Sorry this is very poorly documented, I'm scrapped for time these days 😅 

Would you like me to close this PR and make changes on a separate one?

**Comment by ramojus** [comment]
> Thanks for the PR, and for trying to figure out what was going on here. Sorry this is very poorly documented, I'm scrapped for time these days :sweat_smile:

No worries, thank you for making this project!

> Would you like me to close this PR and make changes on a separate one?

Sure! too many useless commits in this one :)

**Comment by kdheepak** [comment]
Great I’ll do that! I’ll do that some time this weekend. 

Happy holidays and happy new years!

**Pull request closed without merging**
