### PR TITLE
fix(demojify): Do not remove U+0023 # Number Sign

### PR DESCRIPTION
**Pull request by mikesmithgh**
👋 I noticed that the `#` number symbol is being removed from my bash code blocks. The demojify function is targeting `#` as if it is an emoji.

I see `Demojify.lua` is from https://github.com/buildthomas/Demojify/tree/master but I do not know if that project is still maintained. Let me know if you think I should open a PR to the upstream repo as well.

Thanks!
 
*before fix*
```sh
./panvimdoc.sh --project-name testing  --input-file "README.md" --toc false --demojify true && cat doc/testing.txt
SCRIPTS
pandoc --citeproc --shift-heading-level-by=0 --metadata=project:testing --metadata=vimversion: --metadata=toc:false --metadata=description: --metadata=dedupsubheadings:true --metadata=ignorerawblocks:true --metadata=docmapping:false --metadata=docmappingproject:true --metadata=treesitter:true --metadata=incrementheadinglevelby:0 --lua-filter=scripts/include-files.lua --lua-filter=scripts/skip-blocks.lua --data-dir=scripts/../lib --lua-filter=scripts/remove-emojis.lua -t scripts/panvimdoc.lua README.md -o doc/testing.txt
*testing.txt*                For                Last change: 2023 September 12

>bash
     this is a comment
    touch doc/${VIMDOC_PROJECT_NAME}.txt
    git commit -am "Add empty doc"
    git push
<

Generated by panvimdoc <https://github.com/kdheepak/panvimdoc>

vim:tw=78:ts=8:noet:ft=help:norl:
```
*after fix*
```sh
./panvimdoc.sh --project-name testing  --input-file "README.md" --toc false --demojify true && cat doc/testing.txt
SCRIPTS
pandoc --citeproc --shift-heading-level-by=0 --metadata=project:testing --metadata=vimversion: --metadata=toc:false --metadata=description: --metadata=dedupsubheadings:true --metadata=ignorerawblocks:true --metadata=docmapping:false --metadata=docmappingproject:true --metadata=treesitter:true --metadata=incrementheadinglevelby:0 --lua-filter=scripts/include-files.lua --lua-filter=scripts/skip-blocks.lua --data-dir=scripts/../lib --lua-filter=scripts/remove-emojis.lua -t scripts/panvimdoc.lua README.md -o doc/testing.txt
*testing.txt*                For                Last change: 2023 September 12

>bash
    # this is a comment
    touch doc/${VIMDOC_PROJECT_NAME}.txt
    git commit -am "Add empty doc"
    git push
<

Generated by panvimdoc <https://github.com/kdheepak/panvimdoc>

vim:tw=78:ts=8:noet:ft=help:norl:
```

### CODE REVIEW

**Comment by kdheepak** [comment]
Thanks for the PR! I didn’t realize that wasn’t maintained. 

Would you be able to add a test for this? If not, I can add one later and then merge.

**Comment by mikesmithgh** [comment]
> Thanks for the PR! I didn’t realize that wasn’t maintained.
> 
> Would you be able to add a test for this? If not, I can add one later and then merge.

Sure I'll give it a shot

**Comment by mikesmithgh** [comment]
@kdheepak Added tests 👍

**Comment by kdheepak** [comment]
Awesome! Haven't had a chance to look at the PR yet but thanks for doing this!

**Comment by kdheepak** [comment]
That looks great! Thanks again for submitting a PR! I think we should also upstream this fix, I bet the author would appreciate it. 

Would you like to do it? I don't want to give you more work to do but also want you to get credit for your fix :)

**Comment by mikesmithgh** [comment]
done and done https://github.com/buildthomas/Demojify/pull/4 🙂 thanks!

**Comment by kdheepak** [comment]
Awesome! Thank you!

**Pull request merged**
